export const returnPenaltyValuesKorean = {
	FIREARMS: '반입 - 화기류',
	WEAPON: '반입 - 흉기',
	ALCOHOL: '반입 - 주류',
	TOBACCO: '반입 - 담배',
	MEANDERING_APPARATUS: '반입 - 사행성기구',
	FOOD: '반입 - 음식',
	USE_FIREARMS: '사용 - 화기류',
	USE_WEAPON: '사용 - 흉기',
	DRINKING_ALCOHOL: '사용 - 주류',
	USE_TOBACCO: '사용 - 담배',
	USE_MEANDERING_APPARATUS: '사용 - 사행성기구',
	EAT_FOOD: '사용 - 음식',
	MANAGER_GUIDANCE: '사감의 학습 및 생활지도 불이행',
	TIME: '지각',
	OUTING: '외출',
	OVERNIGHT_STAY: '외박',
	DAMAGE_OF_GOODS: '물품훼손',
	THEFT: '절도',
	CHANTAGE: '갈취',
	DISTURBING_SLEEP: '타호실 출입',
	ELECTRONIC_DEVICE: '전자기기 소지',
	LOUD: '고성방가',
	INCORRECT_ENTRY: '지정시간 외 기숙사 출입',
	LAUNDRY: '세탁기,건조기에 세탁물 방치',
	VIOLATION_OF_THE_USE_OF_FACILITIES: '공공시설물 사용규정 위반',
	DAMAGE_OF_POST: '부착된 게시물 훼손 및 낙서',
	POSSESSION_OF_ELECTRONICS_DEVICES: '전자기기 소지 혹은 사용',
	CLEAN_COUNDITION_BAD: '호실 정리정돈 상태 불량',
	ENVIRONMENT_POLLUTION: '기숙사 환경 오염',
	AFFECTIONATE_ACT: '애정 행위',
	SEXUAL_ACT: '성적 행위',
	ENTRY_TO_PROHIBITED_AREAS: '출입금지 구역 출입',
	VIOLATION_OF_STUDY_ROOM_RULES: '학습실 면학분위기 저해',
	OUTSIDER_ENTRY: '외부인 출입 허가',
	'': '',
};

export const returnPenaltyValuesEnglish = {
	'반입 - 화기류': 'FIREARMS',
	'반입 - 흉기': 'WEAPON',
	'반입 - 주류': 'ALCOHOL',
	'반입 - 담배': 'TOBACCO',
	'반입 - 사행성기구': 'MEANDERING_APPARATUS',
	'반입 - 음식': 'FOOD',
	'사용 - 화기류': 'USE_FIREARMS',
	'사용 - 흉기': 'USE_WEAPON',
	'사용 - 주류': 'DRINKING_ALCOHOL',
	'사용 - 담배': 'USE_TOBACCO',
	'사용 - 사행성기구': 'USE_MEANDERING_APPARATUS',
	'사용 - 음식': 'EAT_FOOD',
	'사감의 학습 및 생활지도 불이행': 'MANAGER_GUIDANCE',
	지각: 'TIME',
	외출: 'OUTING',
	외박: 'OVERNIGHT_STAY',
	물품훼손: 'DAMAGE_OF_GOODS',
	절도: 'THEFT',
	갈취: 'CHANTAGE',
	'타호실 출입': 'DISTURBING_SLEEP',
	'전자기기 소지': 'ELECTRONIC_DEVICE',
	고성방가: 'LOUD',
	'지정시간 외 기숙사 출입': 'INCORRECT_ENTRY',
	'세탁물 방치': 'LAUNDRY',
	'공공시설물 사용규정 위반': 'VIOLATION_OF_THE_USE_OF_FACILITIES',
	'부착된 게시물 훼손': 'DAMAGE_OF_POST',
	'전자기기 소지 혹은 사용': 'POSSESSION_OF_ELECTRONICS_DEVICES',
	'호실 정리정돈 상태 불량': 'CLEAN_COUNDITION_BAD',
	'기숙사 환경 오염': 'ENVIRONMENT_POLLUTION',
	'애정 행위': 'AFFECTIONATE_ACT',
	'성적 행위': 'SEXUAL_ACT',
	'출입 금지 구역 출입': 'ENTRY_TO_PROHIBITED_AREAS',
	'학습실 면학분위기 저해': 'VIOLATION_OF_STUDY_ROOM_RULES',
	'외부인 출입 허가': 'OUTSIDER_ENTRY',
	'': '',
};
